// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPyCFoihtlwNBW9OViwfUz0lXw28nrDHQ',
    appId: '1:24170906633:web:421701bf20a839601be4d8',
    messagingSenderId: '24170906633',
    projectId: 'qeasy-7a577',
    authDomain: 'qeasy-7a577.firebaseapp.com',
    storageBucket: 'qeasy-7a577.firebasestorage.app',
    measurementId: 'G-6Z9N2ZZCCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC30U3PuaDDmjquO_Pj0zmxs3C_USbseGw',
    appId: '1:24170906633:android:c8571cf007df4fb11be4d8',
    messagingSenderId: '24170906633',
    projectId: 'qeasy-7a577',
    storageBucket: 'qeasy-7a577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGXRUfQPMA9XHoIViz1oFhvjRHpSvwVYc',
    appId: '1:24170906633:ios:a0b83e84405810941be4d8',
    messagingSenderId: '24170906633',
    projectId: 'qeasy-7a577',
    storageBucket: 'qeasy-7a577.firebasestorage.app',
    iosBundleId: 'com.example.qeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGXRUfQPMA9XHoIViz1oFhvjRHpSvwVYc',
    appId: '1:24170906633:ios:a0b83e84405810941be4d8',
    messagingSenderId: '24170906633',
    projectId: 'qeasy-7a577',
    storageBucket: 'qeasy-7a577.firebasestorage.app',
    iosBundleId: 'com.example.qeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPyCFoihtlwNBW9OViwfUz0lXw28nrDHQ',
    appId: '1:24170906633:web:b00bcc9b6bf3413a1be4d8',
    messagingSenderId: '24170906633',
    projectId: 'qeasy-7a577',
    authDomain: 'qeasy-7a577.firebaseapp.com',
    storageBucket: 'qeasy-7a577.firebasestorage.app',
    measurementId: 'G-0T8PS33ZG1',
  );
}
